import { readFile, stat } from "node:fs/promises";
import { pages, regions, site } from "../data/pages.mjs";

const root = new URL("../", import.meta.url);
const base = site.baseUrl.replace(/\/$/, "");
const requiredRegionSlugs = [
  "logistieke-beveiliging-limburg",
  "beveiliging-distributiecentrum-venlo",
  "logistieke-beveiliging-sittard-geleen",
  "logistieke-beveiliging-roermond",
  "logistieke-beveiliging-weert",
  "logistieke-beveiliging-born-stein"
];
const requiredServiceSlugs = [
  "warehouse-beveiliging",
  "transportbeveiliging",
  "toegangscontrole-logistiek-centrum",
  "nachtbeveiliging-transportbedrijf",
  "beveiliging-bedrijventerrein-logistiek",
  "beveiliging-fulfilmentcentrum"
];

function fail(message) {
  throw new Error(message);
}

function assert(condition, message) {
  if (!condition) fail(message);
}

function canonical(slug) {
  return `${base}/${slug}/`;
}

function tokens(page) {
  const text = [
    page.title,
    page.description,
    page.intent,
    page.intro,
    ...page.context,
    ...page.risks.flatMap((item) => [item.title, item.text]),
    ...page.approach.flatMap((item) => [item.title, item.text]),
    ...page.faq.flatMap((item) => [item.question, item.answer])
  ].join(" ").toLowerCase();
  const stop = new Set(["de", "het", "een", "en", "of", "voor", "van", "met", "op", "in", "te", "is", "zijn", "wordt", "die", "dat", "bij", "naar", "als", "kan", "we", "niet", "ook", "om", "per", "aan", "door"]);
  return new Set(text.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").match(/[a-z0-9]{4,}/g)?.filter((word) => !stop.has(word)) ?? []);
}

function jaccard(a, b) {
  const intersection = [...a].filter((item) => b.has(item)).length;
  const union = new Set([...a, ...b]).size;
  return union ? intersection / union : 0;
}

function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

async function exists(path) {
  try {
    await stat(new URL(path, root));
    return true;
  } catch {
    return false;
  }
}

function readJsonLd(html) {
  const matches = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)];
  return matches.map((match) => JSON.parse(match[1]));
}

const bySlug = new Map(pages.map((page) => [page.slug, page]));
assert(bySlug.size === pages.length, "Slugs are not unique.");
assert(new Set(pages.map((page) => page.title)).size === pages.length, "Titles are not unique.");
assert(new Set(pages.map((page) => canonical(page.slug))).size === pages.length, "Canonicals are not unique.");

for (const slug of requiredRegionSlugs) assert(bySlug.get(slug)?.kind === "region", `Missing required region ${slug}.`);
for (const slug of requiredServiceSlugs) assert(bySlug.get(slug)?.kind === "service", `Missing required service ${slug}.`);

for (const page of pages) {
  for (const field of ["kind", "slug", "title", "metaTitle", "description", "label", "updated", "areaServed", "intent", "intro", "context", "risks", "approach", "faq", "related"]) {
    assert(page[field] && (!Array.isArray(page[field]) || page[field].length), `${page.slug} missing ${field}.`);
  }
  assert(page.context.length >= 3, `${page.slug} needs at least 3 context blocks.`);
  assert(page.risks.length >= 4, `${page.slug} needs at least 4 risks.`);
  assert(page.approach.length >= 4, `${page.slug} needs at least 4 approach/deliverable items.`);
  assert(page.faq.length >= 3, `${page.slug} needs at least 3 FAQ items.`);
  assert(page.related.every((slug) => bySlug.has(slug)), `${page.slug} has a broken related slug.`);
  assert(!page.related.includes(page.slug), `${page.slug} links to itself.`);
}

const comparisons = [];
const regionTokens = regions.map((page) => [page.slug, tokens(page)]);
for (let i = 0; i < regionTokens.length; i++) {
  for (let j = i + 1; j < regionTokens.length; j++) comparisons.push(jaccard(regionTokens[i][1], regionTokens[j][1]));
}
const regionalMedian = median(comparisons);
assert(regionalMedian < 0.35, `Median regional token-set Jaccard is ${regionalMedian.toFixed(3)}, expected < 0.35.`);

for (const page of pages) {
  const htmlPath = `${page.slug}/index.html`;
  assert(await exists(htmlPath), `${htmlPath} was not generated.`);
  const html = await readFile(new URL(htmlPath, root), "utf8");
  assert(html.includes("Generated by scripts/generate-site.mjs from data/pages.mjs."), `${page.slug} missing generated marker.`);
  assert(html.includes(`<link rel="canonical" href="${canonical(page.slug)}">`), `${page.slug} missing canonical.`);
  assert(html.includes('<meta name="robots" content="index, follow, max-image-preview:large">'), `${page.slug} missing robots meta.`);
  assert(html.includes(`property="og:url" content="${canonical(page.slug)}"`), `${page.slug} missing OG url.`);
  assert(html.includes('aria-label="Breadcrumb"'), `${page.slug} missing visible breadcrumbs.`);
  assert(html.includes("Veelgestelde vragen"), `${page.slug} missing FAQ section.`);
  assert(!/AIEO|SEO-cluster|zoekmachines krijgen/i.test(html), `${page.slug} contains public internal SEO/AIEO explanation.`);
  for (const related of page.related) assert(html.includes(`href="/${related}/"`), `${page.slug} missing related link ${related}.`);
  const graphs = readJsonLd(html).flatMap((json) => json["@graph"] ?? [json]);
  for (const type of ["Service", "FAQPage", "BreadcrumbList"]) assert(graphs.some((item) => item["@type"] === type), `${page.slug} missing ${type} JSON-LD.`);
}

const home = await readFile(new URL("index.html", root), "utf8");
for (const page of pages) assert(home.includes(`href="/${page.slug}/"`), `Homepage missing crawlable link to ${page.slug}.`);
const sitemap = await readFile(new URL("sitemap.xml", root), "utf8");
for (const page of pages) assert(sitemap.includes(canonical(page.slug)), `Sitemap missing ${page.slug}.`);
const robots = await readFile(new URL("robots.txt", root), "utf8");
assert(robots.includes(`${base}/sitemap.xml`), "robots.txt missing sitemap.");
const llms = await readFile(new URL("llms.txt", root), "utf8");
for (const page of pages) assert(llms.includes(canonical(page.slug)), `llms.txt missing ${page.slug}.`);

console.log(`Validated ${pages.length} generated pages.`);
console.log(`Median regional token-set Jaccard: ${regionalMedian.toFixed(3)}.`);
console.log("Data, canonical, schema, related links, homepage, sitemap, robots and llms checks passed.");
